apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-conf
data:
  configuration: |
    logging {
        level  = "info"
        format = "logfmt"
    }

    local.file_match "logs" {
        path_targets = [
            {__path__ = "/etc/alloy/*.log"},
        ]
    }

    loki.source.file "tmpfiles" {
        targets    = local.file_match.logs.targets
        forward_to = [loki.write.local.receiver]
    }

    loki.write "local" {
        endpoint {
            url = "http://127.0.0.1:3100/loki/api/v1/push"
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-conf
data:
  configuration: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      log_level: debug
      grpc_server_max_concurrent_streams: 1000

    common:
      instance_addr: 127.0.0.1
      path_prefix: /tmp/loki
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2026-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    frontend:
      encoding: protobuf

    analytics:
      reporting_enabled: false
---
apiVersion: v1
kind : Pod
metadata:
  name: logging
spec:
  containers:
    - name: web
      image: docker.io/grafana/grafana:12.4.0-20629732093
      ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: tcp
      volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana:Z

    - name: db
      image: docker.io/grafana/loki:3.6.4
      ports:
        - containerPort: 3100
          hostPort: 3100
          protocol: tcp
      volumeMounts:
        - name: loki-config
          mountPath: /mnt/config/loki-config.yaml
          subPath: configuration
      args:
        - -config.file=/mnt/config/loki-config.yaml

    - name: agent
      image: docker.io/grafana/alloy:v1.12.2
      ports:
        - containerPort: 12345
          hostPort: 12345
          protocol: tcp
      volumeMounts:
        - name: alloy-config
          mountPath: /etc/alloy/config.alloy
          subPath: configuration
      args:
        - run
        - --server.http.listen-addr=0.0.0.0:12345
        - --storage.path=/var/lib/alloy/data
        - /etc/alloy/config.alloy

  volumes:
    - name: grafana-data
      hostPath:
        path: ${HOST_PATH}/grafana

    - name: alloy-config
      configMap:
        name: alloy-conf

    - name: loki-config
      configMap:
        name: loki-conf
