apiVersion: v1
kind: Pod
metadata:
  name: plantuml
spec:
  containers:
    - name: server
      image: plantuml/plantuml-server:jetty-v1.2024.6
      env:
        - name: BASE_URL
          value: plantuml
      ports:
        - containerPort: 8080
          hostPort: 28080
          protocol: tcp
