apiVersion: v1
kind: Secret
metadata:
  name: hedgedoc-db-cred
data:
  username: ${DB_USER}
  password: ${DB_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: hedgedoc-web-conf
data:
  db_url: ${CMD_DB_URL}
---
apiVersion: v1
kind : Pod
metadata:
  name: hedgedoc
spec:
  containers:
    - name: web
      image: quay.io/hedgedoc/hedgedoc:1.10.1
      env:
        - name: CMD_DOMAIN
          value: localhost
        - name: CMD_URL_ADDPORT
          value: true
        - name: CMD_DB_URL
          valueFrom:
            secretKeyRef:
              name: hedgedoc-web-conf
              key: db_url
        - name: CMD_ALLOW_ANONYMOUS
          value: false
        - name: CMD_DEFAULT_PERMISSION
          value: limited
        - name: CMD_ALLOW_EMAIL_REGISTER
          value: false
      ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: tcp
      # https://github.com/containers/podman/issues/17583
      #volumeMounts:
      #  - name: hedgedoc-files
      #    mountPath: /hedgedoc/public/uploads:Z

    - name: db
      image: docker.io/postgres:16-alpine
      env:
        - name: POSTGRES_DB
          value: hedgedoc
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: hedgedoc-db-cred
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hedgedoc-db-cred
              key: password
      volumeMounts:
        - name: hedgedoc-db
          mountPath: /var/lib/postgresql/data:Z

  volumes:
    - name: hedgedoc-db
      hostPath:
        path: ${HOST_PATH}/db

    - name: hedgedoc-files
      hostPath:
        path: ${HOST_PATH}/files
