apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-conf
data:
  configuration: |
    acl localnet src 10.0.0.0/8
    acl localnet src 169.254.0.0/16
    acl localnet src 172.16.0.0/12
    acl localnet src 192.168.0.0/16

    acl SSL_ports port 443
    acl Safe_ports port 80
    acl Safe_ports port 443

    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports

    http_access deny manager

    http_access allow localnet
    http_access deny all

    http_port 3128
---
apiVersion: v1
kind : Pod
metadata:
  name: squid
spec:
  containers:
    - name: cache
      image: localhost/squid:latest
      ports:
        - containerPort: 3128
          hostPort: 3128
          protocol: tcp
      volumeMounts:
        - name: squid-config
          mountPath: /etc/squid/squid.conf
          subPath: configuration
  volumes:
    - name: squid-config
      configMap:
        name: squid-conf
