apiVersion: v1
kind: ConfigMap
metadata:
  name: growi-web-conf
data:
  growi-url: http://${EXTERNAL_HOST}:23000/
  plantuml-url: http://${EXTERNAL_HOST}:23000/_/uml/
  drawio-url: http://${EXTERNAL_HOST}:23000/_/draw/
  drawio-base-url: http://${EXTERNAL_HOST}:23000/_/draw
  drawio-viewer-url: http://${EXTERNAL_HOST}:23000/_/draw/js/viewer.min.js
  drawio-export-url: http://${EXTERNAL_HOST}:23000/_/export/
  nginx-conf: |
    map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
    }

    server {
      listen 80;

      proxy_set_header    Host               $proxy_host;
      proxy_set_header    X-Real-IP          $remote_addr;
      proxy_set_header    X-Forwarded-Proto  $scheme;
      proxy_set_header    X-Forwarded-Host   $http_host;
      proxy_set_header    X-Forwarded-Server $host;
      proxy_set_header    X-Forwarded-Port   $server_port;
      proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;

      # for WebSocket
      proxy_set_header    Upgrade            $http_upgrade;
      proxy_set_header    Connection         $connection_upgrade;

      location / {
        # https://github.com/weseek/growi/issues/748
        proxy_pass http://127.0.0.1:3000/;
      }

      location /_/uml/ {
        proxy_pass http://127.0.0.1:8081/_/uml/;
      }

      location /_/draw/js/viewer.min.js {
        # apps/app/src/components/Script/DrawioViewerScript.tsx:44
        # new URL('/js/viewer.min.js', rendererConfig.drawioUri)
        # URL の引数が絶対パスのため PATH が無視されるので draw.io に変更する。
        # 上記の問題は修正されたが windows オブジェクトに PATH を設定するため、
        # injection は残す。
        # https://github.com/weseek/growi/pull/8878
        proxy_pass http://127.0.0.1/_/www/viewer-injection.js;
      }

      location /_/draw/ {
        proxy_pass http://127.0.0.1:8082/_/draw/;
      }

      location /_/export/ {
        rewrite /_/export/(.*) /$1 break;
        proxy_pass http://127.0.0.1:8000/;
      }

      location /_/www/ {
        rewrite /_/www/(.*) /$1 break;
        root /var/www;
      }
    }
  drawio-viewer-inject: |
    window.PROXY_URL = "/_/draw/proxy";
    window.STYLE_PATH = "/_/draw/styles";
    window.SHAPES_PATH = "/_/draw/shapes";
    window.STENCIL_PATH = "/_/draw/stencils";
    window.GRAPH_IMAGE_PATH = "/_/draw/img";
    window.mxImageBasePath = "/_/draw/mxgraph/images";

    let block = document.createElement('script');
    block.src = '/_/draw/js/viewer-static.min.js';
    document.head.appendChild(block);
---
apiVersion: v1
kind: Secret
metadata:
  name: growi-wiki-conf
data:
  password-seed: ${PASSWORD_SEED}
  secret-token: ${SECRET_TOKEN}
---
apiVersion: v1
kind: Pod
metadata:
  name: growi
spec:
  containers:
    - name: web
      image: docker.io/nginx:1.27.1-alpine3.20-slim
      ports:
        - containerPort: 80
          hostPort: 23000
          protocol: tcp
      volumeMounts:
        - name: growi-web-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx-conf
        - name: growi-web-conf
          mountPath: /var/www/viewer-injection.js
          subPath: drawio-viewer-inject

    - name: wiki
      image: docker.io/weseek/growi:7.0.17
      env:
        - name: APP_SITE_URL
          valueFrom:
            configMapKeyRef:
              name: growi-web-conf
              key: growi-url
        - name: MONGO_URI
          value: mongodb://127.0.0.1/growi
        - name: ELASTICSEARCH_VERSION
          value: 8
        - name: ELASTICSEARCH_URI
          value: http://127.0.0.1:9200/growi
        - name: PLANTUML_URI
          valueFrom:
            configMapKeyRef:
              name: growi-web-conf
              key: plantuml-url
        - name: DRAWIO_URI
          valueFrom:
            configMapKeyRef:
              name: growi-web-conf
              key: drawio-url
        - name: PASSWORD_SEED
          valueFrom:
            secretKeyRef:
              name: growi-wiki-conf
              key: password-seed
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: growi-wiki-conf
              key: secret-token
        - name: DEFAULT_EMAIL_PUBLISHED
          value: false
        - name: AUDIT_LOG_ENABLED
          value: true
        - name: FILE_UPLOAD
          value: local
      volumeMounts:
        - name: growi-data
          mountPath: /data:Z

    - name: db
      image: docker.io/mongo:7.0.14-jammy
      volumeMounts:
        - name: growi-db
          mountPath: /data/db:Z
        - name: growi-configdb
          mountPath: /data/configdb:Z

    - name: uml
      image: localhost/plantuml-server:jetty-v1.2024.6-ex
      env:
        - name: BASE_URL
          value: /_/uml/
        - name: PORT
          value: 8081
      args:
        - --module=http-forwarded

    - name: draw
      image: localhost/drawio:24.7.8-ex
      env:
        - name: BASE_URL
          value: /_/draw/
        - name: PORT
          value: 8082
        - name: DRAWIO_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: growi-web-conf
              key: drawio-url
        - name: DRAWIO_VIEWER_URL
          valueFrom:
            configMapKeyRef:
              name: growi-web-conf
              key: drawio-viewer-url
        - name: DRAWIO_LIGHTBOX_URL
          valueFrom:
            configMapKeyRef:
              name: growi-web-conf
              key: drawio-viewer-url
        - name: EXPORT_URL
          valueFrom:
            configMapKeyRef:
              name: growi-web-conf
              key: drawio-export-url
        - name: PLANT_URL
          valueFrom:
            configMapKeyRef:
              name: growi-web-conf
              key: plantuml-url

    - name: export
      image: localhost/export-server:ex
      env:
        - name: DRAWIO_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: growi-web-conf
              key: drawio-base-url

    - name: search
      image: localhost/elasticsearch:8.15.0-ex
      env:
        - name: discovery.type
          value: single-node
      volumeMounts:
        - name: growi-index
          mountPath: /usr/share/elasticsearch/data:Z

  volumes:
    - name: growi-data
      hostPath:
        path: ${HOST_PATH}/data

    - name: growi-db
      hostPath:
        path: ${HOST_PATH}/db

    - name: growi-configdb
      hostPath:
        path: ${HOST_PATH}/configdb

    - name: growi-index
      hostPath:
        path: ${HOST_PATH}/index

    - name: growi-web-conf
      configMap:
        name: growi-web-conf
